# Generated by Django 5.2.7 on 2026-01-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_company_address_order_company_cif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5),
        ),
    ]
