# Generated by Django 5.2.7 on 2026-01-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('PICKUP', 'Recogida en tienda'), ('DELIVERY', 'Envío a domicilio')], default='PICKUP', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_slot',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
