# Generated by Django 5.2.7 on 2026-01-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_address_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CART', 'Carrito'), ('PENDING', 'Pendiente'), ('PREPARING', 'Preparando'), ('READY', 'Listo'), ('IN_TRANSIT', 'En camino'), ('DONE', 'Entregado'), ('CANCELLED', 'Cancelado')], default='CART', max_length=15),
        ),
    ]
